#!/bin/bash

set -eu


export REGION=$(curl -sS http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
export CLUSTER_NAME=flexible-compute-cluster
export KUBECTL_VERSION=v1.21.2
export AWS_DEFAULT_REGION=$(curl -sS http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

echo "export CLUSTER_NAME=flexible-compute-cluster" >> ~/.bash_profile
echo "export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> ~/.bash_profile
echo "export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> ~/.bash_profile

echo 'Installing eksctl'
curl --silent --location https://github.com/weaveworks/eksctl/releases/download/v0.87.0/eksctl_Linux_amd64.tar.gz | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin


echo 'Installing kubectl'
sudo curl --silent --location -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
sudo chmod +x /usr/local/bin/kubectl

echo 'Creating an EKS cluster'
eksctl create cluster -f ../cluster.yaml


echo 'Configuring EKS context'
aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME


echo 'Installing helm...'
curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

echo 'Deploying the metrics server'
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.0/components.yaml

echo
echo
echo
echo '############################'
echo '#######   done   ###########'
echo '############################'