#!/bin/bash

set -eu

echo "Removing unneeded docker images..."
docker images -q | xargs docker rmi || true

echo "Installing dependencies..."
sudo yum install -y jq bash-completion

echo "Fetching CloudFormation outputs..."
script/fetch-outputs

echo "Attaching Instance Profile to Cloud9..."
script/associate-profile

echo "Configuring Cloud9..."
script/configure-cloud9

echo "Cleaning cached credential..."
rm -vf ${HOME}/.aws/credentials

echo "Success!"