---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
- us-east-1a
- us-east-1b
- us-east-1c
metadata:
  name: flexible-compute-cluster
  region: ${AWS_REGION}
  version: "1.21"
  tags:
    karpenter.sh/discovery: flexible-compute-cluster
iam:
  withOIDC: true
managedNodeGroups:
- amiFamily: AmazonLinux2
  instanceType: m5.large
  name: mng-od-m5large
  desiredCapacity: 1
  maxSize: 1
  minSize: 0
  labels:
    alpha.eksctl.io/cluster-name: flexible-compute-cluster
    alpha.eksctl.io/nodegroup-name: mng-od-m5large
    intent: control-apps
  tags:
    alpha.eksctl.io/nodegroup-name: mng-od-m5large
    alpha.eksctl.io/nodegroup-type: managed
    k8s.io/cluster-autoscaler/node-template/label/intent: control-apps
  iam:
    withAddonPolicies:
      autoScaler: true
      cloudWatch: true
      albIngress: true
  privateNetworking: true